@startuml
title UML-діаграма розгортання інформаційної системи розпізнавання мови жестів

node "Користувач" {
    [Мобільний пристрій]
    [Робоча станція користувача]
}

node "Серверне середовище" {
    node "Сервер" {
        [Сервер бази даних (SQLite)]
        [Сервер розпізнавання жестів]
        [Веб-сервер для інтерфейсу]
    }
    node "Система управління відеопотоком" {
        [Камера для збору даних жестів]
    }
}

node "Канал зв'язку" {
    [Інтернет-з'єднання]
    [Бездротовий канал зв’язку (Wi-Fi)]
}

node "Клієнтська частина" {
    [Інтерфейс користувача (веб, мобільний додаток)]
}

[Камера для збору даних жестів] -down-> [Сервер розпізнавання жестів] : надсилає відеопотік
[Сервер розпізнавання жестів] --> [Сервер бази даних (SQLite)] : зберігає розпізнані жести
[Сервер розпізнавання жестів] --> [Веб-сервер для інтерфейсу] : надсилає результати розпізнавання
[Веб-сервер для інтерфейсу] --> [Інтерфейс користувача (веб, мобільний додаток)] : надає доступ до результатів

[Користувач] --> [Інтерфейс користувача (веб, мобільний додаток)] : отримує дані розпізнавання
@enduml
